config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :users
    
  resource :user_sessions, :only => [:create, :new, :destroy]

    root 'home#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
    
    belongs_to :user
    
    validates_presence_of :day, :hour, :user_id
    
    def self.reservado(dia, hora)
        location = where (['day LIKE :dia AND hour LIKE :hora', :dia => "%#{dia}%", :hora => "%#{hora}%"])
        location.first
    
        #where('hour=? OR day=?', :hora, :dia)
    end
        
end

app/models/user.rb
class User < ActiveRecord::Base
    
    validates_presence_of :name, :email
    validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
    validates_uniqueness_of :email
    
    has_secure_password
    
   def self.authenticate(email, password)
    find_by_email(email).
    try(:authenticate, password)
   end 
    
end

app/models/user_session.rb
class UserSession
    include ActiveModel::Validations
    include ActiveModel::Conversion
    
    extend ActiveModel::Translation
    extend ActiveModel::Naming
    
    attr_accessor :email, :password
    
    def initialize(session, attributes={})
        @session = session
        @email = attributes[:email]
        @password = attributes[:password]
    end
    
    def authenticate
        user = User.authenticate(@email, @password)
        if user.present?
            store(user)
        else
            errors.add(:base, :invalid_login)
            false
        end
    end
    
    def store(user)
        @session[:user_id] = user.id
    end
    
    def persisted?
        false
    end
    
    def current_user
        User.find(@session[:user_id])
    end
    
    def user_signed_in?
        @session[:user_id].present?
    end
    def destroy
        @session[:user_id] = nil
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
    
  delegate :current_user, :user_signed_in?, :to => :user_session
  helper_method :current_user, :user_signed_in?, :reservado
  
  def user_session
    UserSession.new(session)
  end
    
  def require_authentication
    unless user_signed_in?
      redirect_to new_user_sessions_path
    end
  end
    
    def require_no_authentication
        redirect_to root_path if user_signed_in?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_filter :require_authentication
    
    def index
    end
    
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_filter :require_authentication,
:only => [:new, :edit, :create, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
        params.require(:location).permit(:day, :hour, :user_id)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    before_filter :require_no_authentication, :only => [:new, :create]
    before_filter :require_authentication, :only => :destroy
    
    def new
        @session = UserSession.new(session)
    end
    
    def create
        @session = UserSession.new(session, params[:user_session])
        if @session.authenticate
            redirect_to root_path
        else
            render :new
        end
    end
    
    def destroy
        user_session.destroy
        redirect_to root_path, :notice => t('flash.notice.signed_out')
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<table>
    <thead>
        <tr>
            <th>Horario</th>
            <th>Segunda-feira</th>
            <th>Terça-feira</th>
            <th>Quarta-feira</th>
            <th>Quinta-feira</th>
            <th>Sexta-Feira</th>
        </tr>
    </thead>
    <tbody>
        <% for horario in 6..22 %>
            <tr>
                <td><%= horario %>:00</td>
                <% for dia in 1..5 %>
                    <td>
                        <% location = Location.reservado(dia, horario) %>
                        <% if location == nil %>
                            <%= form_for Location.new, :remote => true do |f| %>
                                <%= f.hidden_field :day, value: dia %>
                                <%= f.hidden_field :hour, value: horario %>     
                                <%= f.hidden_field :user_id, value: current_user.id %>
                                <%= f.submit  'Reservar' %>
                        
                            <% end %>
                        <% else %>
                            <% if location.user.name == current_user.name %>
                                <span class="user-reserva user-reserva-voce">Você</span>
                            <% else %>
                                <span class="user-reserva"><%= location.user.name %></span>
                            <% end %>
                        <% end %>
                    </td>   
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>





app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agenda</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <header class="header">
        <div class="title">
            <h1>Agenda de sala</h1>
        </div>
        <% if user_signed_in? %>
            <div class="user">
                <div class="email">
                    <span><%= current_user.email %></span>
                </div>
                <div class="sair">
                    <%= link_to "Sair", user_sessions_path,
    :method => :delete %>    
                </div>
            </div>
        <% end %>
    </header>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :hour %><br>
    <%= f.text_field :hour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Hour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.day %></td>
        <td><%= location.hour %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @location.day %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @location.hour %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
    
<% if @session.errors.has_key? :base %>
    <div id="error_explanation">
        <%= @session.errors[:base].join(', ')%>
    </div>
<% end %>
<%= form_for @session do |f| %>
    <p>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </p>
    <p>
        <%= f.label :Senha %>
        <%= f.password_field :password %>
    </p>
    <p>
        <%= f.submit 'Entrar'%>       
    </p>
<% end %>           
    
    
                

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Senha:</strong>
    <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>